image:
  file: .gitpod/Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: |
      mysql -u root -e "create database laravel" && \
      cp .env.example .env && \
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env && \
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env && \
      composer install && \
      npm install && \
      php artisan key:generate
    command: |
      php artisan migrate --seed && \
      php artisan serve